In [1]:
# Install required libraries
!pip install pandas numpy scikit-learn

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier

In [3]:
# Fix random values so output is same every time
np.random.seed(42)

n = 50

data = {
    'experience_years': np.random.randint(0, 11, n),
    'test_score': np.random.randint(40, 100, n),
    'interview_score': np.random.randint(40, 100, n),
    'skill_match': np.random.randint(1, 4, n)
}

df = pd.DataFrame(data)

df.head()

   experience_years  test_score  interview_score  skill_match
0                 6          92               99            3
1                 3          41               99            2
2                10          59               84            3
3                 7          67               80            1
4                 4          86               68            1

In [4]:
df['selected'] = (
    ((df['experience_years'] >= 3) &
     (df['test_score'] >= 60) &
     (df['interview_score'] >= 60)) |

    ((df['skill_match'] == 3) &
     (df['interview_score'] >= 70))
).astype(int)

df.head()

   experience_years  test_score  interview_score  skill_match  selected
0                 6          92               99            3         1
1                 3          41               99            2         0
2                10          59               84            3         1
3                 7          67               80            1         1
4                 4          86               68            1         1

In [5]:
X = df[['experience_years', 'test_score', 'interview_score', 'skill_match']]
y = df['selected']

In [6]:
model = DecisionTreeClassifier(max_depth=4, random_state=42)
model.fit(X, y)

DecisionTreeClassifier(max_depth=4, random_state=42)

In [7]:
sample = [[4, 75, 80, 3]]

prediction = model.predict(sample)

prediction

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([1])

In [8]:
if prediction[0] == 1:
    print("Candidate Likely to be Selected")
else:
    print("Candidate Likely to be Rejected")

Candidate Likely to be Selected

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   experience_years  50 non-null     int64
 1   test_score        50 non-null     int64
 2   interview_score   50 non-null     int64
 3   skill_match       50 non-null     int64
 4   selected          50 non-null     int64
dtypes: int64(5)
memory usage: 2.1 KB

In [10]:
df['selected'].value_counts()

selected
0    26
1    24
Name: count, dtype: int64

In [11]:
# Save dataset to CSV file
df.to_csv('hr_recruitment_dataset.csv', index=False)

print("Dataset saved successfully!")

Dataset saved successfully!

In [12]:
from google.colab import files
files.download('hr_recruitment_dataset.csv')